// Entry point for Hostinger LiteSpeed Node.js hosting
// Loads the Next.js standalone server generated by `next build`
const path = require('path')

// Set environment
process.env.NODE_ENV = 'production'
process.env.PORT = process.env.PORT || '3000'
process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0'

// Load standalone server
const standaloneServer = path.join(__dirname, '.next', 'standalone', 'server.js')
require(standaloneServer)
